# Generated by Django 4.2.18 on 2025-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0017_remove_historicalindividualdatasourceupload_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupindividual',
            name='role',
            field=models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('SPOUSE', 'SPOUSE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHER'), ('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDDAUGHTER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('OTHER RELATIVE', 'OTHER RELATIVE'), ('NOT RELATED', 'NOT RELATED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupindividual',
            name='role',
            field=models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('SPOUSE', 'SPOUSE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHER'), ('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDDAUGHTER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('OTHER RELATIVE', 'OTHER RELATIVE'), ('NOT RELATED', 'NOT RELATED')], max_length=255, null=True),
        ),
    ]
