# Generated by Django 4.2.13 on 2024-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0017_remove_historicalindividualdatasourceupload_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupindividual",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="groupindividuals",
                to="individual.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupindividual",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="groupindividuals",
                to="individual.individual",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="groups",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalgroup",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="individuals",
                to="location.location",
            ),
        ),
    ]
