# Generated by Django 4.2.21 on 2025-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0018_alter_groupindividual_group_and_more'),
        ('individual', '0018_alter_groupindividual_role_and_more'),
    ]

    operations = [
    ]
